### PR TITLE
.github/workflows: allow GITHUB_TOKEN to have `write:packages` scope

### PR DESCRIPTION
**Pull request by nikhita**
Should fix the failing action in https://github.com/kubernetes-sigs/community-images/actions/runs/4491155761/jobs/7899218902

```
  • publishing
    • scm releases
      • creating or updating release                 repo=kubernetes-sigs/community-images tag=v0.4.1
  ⨯ release failed after 8m40s               error=scm releases: failed to publish artifacts: could not release: PATCH https://api.github.com/repos/kubernetes-sigs/community-images/releases/96503819: 403 Resource not accessible by personal access token []
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.16.2/x64/goreleaser' failed with exit code 1
```

Ref:
- https://goreleaser.com/quick-start/#:~:text=token%20here.-,Info,-The%20minimum%20permissions
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication

/assign @dims

### CODE REVIEW

**Comment by nikhita** [comment]
/hold

looks like we are using a PAT here.

**Comment by nikhita** [comment]
/hold cancel

Actually, from https://docs.github.com/en/actions/security-guides/automatic-token-authentication, looks like this should also work for a PAT

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
